---

- hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - { role: homebrew, tags: [homebrew] }
    - { role: dotfiles, tags: [dotfiles] }
    - { role: anyenv, tags: [anyenv] }
    - { role: osx_defaults, tags: [osx] }
    - { role: mas, tags: [mas] }
        
    
