
- name: Clone dotfiles repository
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_repo_local_destination }}/dotfiles"
    accept_hostkey: yes

- name: Link dotfiles into home directory
  shell: "./create_symlinks.sh"
  args:
    chdir: "{{ dotfiles_repo_local_destination }}/dotfiles"


- name: Make directory vim-neobundle
  file: path="~/.vim/bundle" state=directory

- name: Install neobundle
  git:
    repo: "{{ neobundle_repo }}"
    dest: "{{ neobundle_repo_local_destination }}"
    accept_hostkey: yes

- name: Make directory vim-color-molokai
  file: path="~/.vim/colors" state=directory

- name: Install vim-color-molokai
  git:
    repo: "{{ vim_color_molokai_repo }}"
    dest: "~/vim-molokai"
    accept_hostkey: yes

- name: Cp vim-molokai to vim-colors-directory
  command: cp ~/vim-molokai/colors/molokai.vim ~/.vim/colors/



