
- name: Add homebrew tap repository
  homebrew_tap: 
    tap: "{{ item }}"
    state: present
  with_items:
    - "{{ homebrew_taps }}"

- name: Update homebrew
  homebrew: 
    update_homebrew: yes

- name: Install brew packages
  homebrew:
    name: "{{ item.name }}"
    state: latest
  with_items:
    "{{ homebrew_packages }}"

- name: Install cask packages
  ignore_errors: True 
  homebrew_cask:
    name: "{{ item.name }}"
    state: present
  with_items:
    - "{{ homebrew_cask_packages }}"
