- name: Install anyenv
  git:
    repo: "{{ anyenv_repository_url }}"
    dest: "~/.anyenv"

- name: Install anyenv plugins
  git:
    repo: "{{ item.repository_url }}"
    dest: "~/.anyenv/plugins/{{ item.name }}"
  with_items:
    - "{{ anyenv_plugins }}"

- name: Create anyenv directory
  file:
    path: "~/.anyenv/envs/{{ item }}"
    state: directory
    mode: 0775
  with_items:
    - "{{ anyenv_envs }}"

- name: Install envs
  shell:
     "anyenv install -s {{ item }}"
  with_items:
    - "{{ anyenv_envs }}"
  args:
    executable: /usr/local/bin/zsh

- name: Update anyenvs
  shell: anyenv update
  args:
    executable: /usr/local/bin/zsh
