anyenv_repository_url: https://github.com/riywo/anyenv

anyenv_plugins:
  - name: anyenv-update
    repository_url: https://github.com/znz/anyenv-update.git

anyenv_envs:
   - goenv
   - jenv
   - nodenv
   - pyenv
   - rbenv
